# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "NiPPE"
version: "0.0.5"
slug: "nippe"
description: "Nibe Power Performance Enhancement"
url: "https://github.com/Wesztman/nippe"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
# image: "ghcr.io/home-assistant/{arch}-addon-example"
image: "ghcr.io/wesztman/nippe/{arch}-nippe"
