name: "NiPPE"
description: "Nibe Power Performance Enhancement"
version: "0.0.1"
slug: "nippe"
url: "https://github.com/Wesztman/nippe"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  8000/tcp: 8000
